package com.sb.curdwithjpa.utlls;

import java.security.SecureRandom;
import java.util.stream.Collectors;

import static com.sb.curdwithjpa.constants.AppConstants.*;

public class AppUtils {
    /**
     * This method is used to generate the random alphanumaric string for the password.
     *
     * @return String autogenerated random value
     */
    public static String generatePassword() {
        SecureRandom random = new SecureRandom();
        return random.ints(PASS_LENGTH, 0, PASS_CHARACTERS.length())
                .mapToObj(PASS_CHARACTERS::charAt)
                .map(Object::toString)
                .collect(Collectors.joining());

    }

    /**
     * This method is used to generate the random numbers for an OTP.
     *
     * @return string 6 digits otp
     */
    public static String generateOtp() {
        SecureRandom random = new SecureRandom();
        return random.ints(OTP_LENGTH, 0, OTP_CHARACTERS.length())
                .mapToObj(OTP_CHARACTERS::charAt)
                .map(Object::toString)
                .collect(Collectors.joining());
    }
}
